create table "public"."Analytics" (
    "id" bigint generated by default as identity not null,
    "event_id" smallint,
    "attendance_count" smallint,
    "engagement_level" character varying,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Analytics" enable row level security;

create table "public"."Attendance" (
    "id" bigint generated by default as identity not null,
    "user_id" smallint,
    "event_id" smallint,
    "scan_time" timestamp without time zone,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Attendance" enable row level security;

create table "public"."Events" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "event_date" timestamp without time zone,
    "location" character varying,
    "entertainer_id" smallint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Events" enable row level security;

create table "public"."QRCodes" (
    "id" bigint generated by default as identity not null,
    "event_id" smallint,
    "created_at" timestamp with time zone not null default now(),
    "qr_code_url" text
);


alter table "public"."QRCodes" enable row level security;

create table "public"."Rewards" (
    "id" bigint generated by default as identity not null,
    "user_id" smallint,
    "points" smallint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Rewards" enable row level security;

create table "public"."Users" (
    "id" bigint generated by default as identity not null,
    "username" character varying,
    "email" character varying,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Users" enable row level security;

CREATE UNIQUE INDEX "Analytics_pkey" ON public."Analytics" USING btree (id);

CREATE UNIQUE INDEX "Attendance_pkey" ON public."Attendance" USING btree (id);

CREATE UNIQUE INDEX "Events_pkey" ON public."Events" USING btree (id);

CREATE UNIQUE INDEX "QRCodes_pkey" ON public."QRCodes" USING btree (id);

CREATE UNIQUE INDEX "Rewards_pkey" ON public."Rewards" USING btree (id);

CREATE UNIQUE INDEX "Users_pkey" ON public."Users" USING btree (id);

alter table "public"."Analytics" add constraint "Analytics_pkey" PRIMARY KEY using index "Analytics_pkey";

alter table "public"."Attendance" add constraint "Attendance_pkey" PRIMARY KEY using index "Attendance_pkey";

alter table "public"."Events" add constraint "Events_pkey" PRIMARY KEY using index "Events_pkey";

alter table "public"."QRCodes" add constraint "QRCodes_pkey" PRIMARY KEY using index "QRCodes_pkey";

alter table "public"."Rewards" add constraint "Rewards_pkey" PRIMARY KEY using index "Rewards_pkey";

alter table "public"."Users" add constraint "Users_pkey" PRIMARY KEY using index "Users_pkey";

grant delete on table "public"."Analytics" to "anon";

grant insert on table "public"."Analytics" to "anon";

grant references on table "public"."Analytics" to "anon";

grant select on table "public"."Analytics" to "anon";

grant trigger on table "public"."Analytics" to "anon";

grant truncate on table "public"."Analytics" to "anon";

grant update on table "public"."Analytics" to "anon";

grant delete on table "public"."Analytics" to "authenticated";

grant insert on table "public"."Analytics" to "authenticated";

grant references on table "public"."Analytics" to "authenticated";

grant select on table "public"."Analytics" to "authenticated";

grant trigger on table "public"."Analytics" to "authenticated";

grant truncate on table "public"."Analytics" to "authenticated";

grant update on table "public"."Analytics" to "authenticated";

grant delete on table "public"."Analytics" to "service_role";

grant insert on table "public"."Analytics" to "service_role";

grant references on table "public"."Analytics" to "service_role";

grant select on table "public"."Analytics" to "service_role";

grant trigger on table "public"."Analytics" to "service_role";

grant truncate on table "public"."Analytics" to "service_role";

grant update on table "public"."Analytics" to "service_role";

grant delete on table "public"."Attendance" to "anon";

grant insert on table "public"."Attendance" to "anon";

grant references on table "public"."Attendance" to "anon";

grant select on table "public"."Attendance" to "anon";

grant trigger on table "public"."Attendance" to "anon";

grant truncate on table "public"."Attendance" to "anon";

grant update on table "public"."Attendance" to "anon";

grant delete on table "public"."Attendance" to "authenticated";

grant insert on table "public"."Attendance" to "authenticated";

grant references on table "public"."Attendance" to "authenticated";

grant select on table "public"."Attendance" to "authenticated";

grant trigger on table "public"."Attendance" to "authenticated";

grant truncate on table "public"."Attendance" to "authenticated";

grant update on table "public"."Attendance" to "authenticated";

grant delete on table "public"."Attendance" to "service_role";

grant insert on table "public"."Attendance" to "service_role";

grant references on table "public"."Attendance" to "service_role";

grant select on table "public"."Attendance" to "service_role";

grant trigger on table "public"."Attendance" to "service_role";

grant truncate on table "public"."Attendance" to "service_role";

grant update on table "public"."Attendance" to "service_role";

grant delete on table "public"."Events" to "anon";

grant insert on table "public"."Events" to "anon";

grant references on table "public"."Events" to "anon";

grant select on table "public"."Events" to "anon";

grant trigger on table "public"."Events" to "anon";

grant truncate on table "public"."Events" to "anon";

grant update on table "public"."Events" to "anon";

grant delete on table "public"."Events" to "authenticated";

grant insert on table "public"."Events" to "authenticated";

grant references on table "public"."Events" to "authenticated";

grant select on table "public"."Events" to "authenticated";

grant trigger on table "public"."Events" to "authenticated";

grant truncate on table "public"."Events" to "authenticated";

grant update on table "public"."Events" to "authenticated";

grant delete on table "public"."Events" to "service_role";

grant insert on table "public"."Events" to "service_role";

grant references on table "public"."Events" to "service_role";

grant select on table "public"."Events" to "service_role";

grant trigger on table "public"."Events" to "service_role";

grant truncate on table "public"."Events" to "service_role";

grant update on table "public"."Events" to "service_role";

grant delete on table "public"."QRCodes" to "anon";

grant insert on table "public"."QRCodes" to "anon";

grant references on table "public"."QRCodes" to "anon";

grant select on table "public"."QRCodes" to "anon";

grant trigger on table "public"."QRCodes" to "anon";

grant truncate on table "public"."QRCodes" to "anon";

grant update on table "public"."QRCodes" to "anon";

grant delete on table "public"."QRCodes" to "authenticated";

grant insert on table "public"."QRCodes" to "authenticated";

grant references on table "public"."QRCodes" to "authenticated";

grant select on table "public"."QRCodes" to "authenticated";

grant trigger on table "public"."QRCodes" to "authenticated";

grant truncate on table "public"."QRCodes" to "authenticated";

grant update on table "public"."QRCodes" to "authenticated";

grant delete on table "public"."QRCodes" to "service_role";

grant insert on table "public"."QRCodes" to "service_role";

grant references on table "public"."QRCodes" to "service_role";

grant select on table "public"."QRCodes" to "service_role";

grant trigger on table "public"."QRCodes" to "service_role";

grant truncate on table "public"."QRCodes" to "service_role";

grant update on table "public"."QRCodes" to "service_role";

grant delete on table "public"."Rewards" to "anon";

grant insert on table "public"."Rewards" to "anon";

grant references on table "public"."Rewards" to "anon";

grant select on table "public"."Rewards" to "anon";

grant trigger on table "public"."Rewards" to "anon";

grant truncate on table "public"."Rewards" to "anon";

grant update on table "public"."Rewards" to "anon";

grant delete on table "public"."Rewards" to "authenticated";

grant insert on table "public"."Rewards" to "authenticated";

grant references on table "public"."Rewards" to "authenticated";

grant select on table "public"."Rewards" to "authenticated";

grant trigger on table "public"."Rewards" to "authenticated";

grant truncate on table "public"."Rewards" to "authenticated";

grant update on table "public"."Rewards" to "authenticated";

grant delete on table "public"."Rewards" to "service_role";

grant insert on table "public"."Rewards" to "service_role";

grant references on table "public"."Rewards" to "service_role";

grant select on table "public"."Rewards" to "service_role";

grant trigger on table "public"."Rewards" to "service_role";

grant truncate on table "public"."Rewards" to "service_role";

grant update on table "public"."Rewards" to "service_role";

grant delete on table "public"."Users" to "anon";

grant insert on table "public"."Users" to "anon";

grant references on table "public"."Users" to "anon";

grant select on table "public"."Users" to "anon";

grant trigger on table "public"."Users" to "anon";

grant truncate on table "public"."Users" to "anon";

grant update on table "public"."Users" to "anon";

grant delete on table "public"."Users" to "authenticated";

grant insert on table "public"."Users" to "authenticated";

grant references on table "public"."Users" to "authenticated";

grant select on table "public"."Users" to "authenticated";

grant trigger on table "public"."Users" to "authenticated";

grant truncate on table "public"."Users" to "authenticated";

grant update on table "public"."Users" to "authenticated";

grant delete on table "public"."Users" to "service_role";

grant insert on table "public"."Users" to "service_role";

grant references on table "public"."Users" to "service_role";

grant select on table "public"."Users" to "service_role";

grant trigger on table "public"."Users" to "service_role";

grant truncate on table "public"."Users" to "service_role";

grant update on table "public"."Users" to "service_role";


